### ISSUE TITLE
Default to the calling shell type when first positional arg isn't present

### ISSUE THREAD

**Issue by joelfourhman** [JohnnyIrvin/shell-craft#35]
Default the request to the type of the calling shell so you don't need to constantly prompt the type of shell/language 

e.g.

(from a bash terminal)
shell-craft write me a thingy    - should return bash

(from a bash terminal)
shell-craft powershell write me a thingy    - should return powershell

**Comment by JohnnyIrvin** [comment]
This might be related to developing this feature: https://stackoverflow.com/questions/55597797/detect-whether-current-shell-is-powershell-in-python

@joelfourhman Should we make the language an optional parameter then? Currently it is a positional.

So instead of 
```
shell-craft python Do a thing
```

It would be something like the following when wanting to not use the shell.

```
shell-craft --lang python Do a thing
```

We will also need to consider non-language prompts or we can drop the "feature_request" prompt entirely and focus solely on code tasks such as code creation, documentation, refactoring, and tests. That would be more inline with single-responsibility principle.

**Comment by joelfourhman** [comment]
I would say yes, or something like that.


maybe:
shell-craft --python Do a thing

^ only when you want something that isn't your calling shell.

**Comment by JohnnyIrvin** [comment]
Alright, fantastic. @joelfourhman 

I'll get to work on this once I set up powershell on my system so that I can test both powershell and bash.

**Comment by joelfourhman** [comment]
We have to be careful of how we implement this because if get just 'collect the window title' or something, then there will be a problems.

For instance:  I'm running WSL inside my powershell terminal. Or I'm running Git bash in my Windows Terminal, etc

**Comment by JohnnyIrvin** [comment]
@joelfourhman We could get the parent process ID and get the process's information and confirm that it is powershell or something similar. Here is a solution using [psutil](https://pypi.org/project/psutil/) which is licensed under BSD.

Ran in a bash terminal.
```
>>> import psutil
>>> import os
>>> psutil.Process(os.getppid()).name()
'bash'
```

Ran in a bash terminal which is running powershell
```
>>> import psutil
>>> import os
>>> psutil.Process(os.getppid()).name()
'pwsh'
```

@joelfourhman Do you know if the name of the process can be otherwise or some other variation in normal installations?

**Comment by joelfourhman** [comment]
That logic works well, I just tested it in a python repl.  Windows Terminal could have really made this more difficult, I'm glad it didn't
 In Windows running that code I get powershell.exe as the response. So we need to account for that.
